dbt_weatherstack:
  outputs:
    dev:
      dbname: weatherstack
      host: host.docker.internal
      pass: airflow
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: airflow
  target: dev
